# preload = ~/Downloads/wallpaper.jpg
# preload = ~/Downloads/tokyo-night-buildings.jpg
preload = ~/Downloads/Distance.gif
wallpaper = eDP-1, ~/Downloads/Distance.gif
# wallpaper = eDP-1, ~/Downloads/tokyo-night-buildings.jpg
wallpaper = HDMI-A-1, ~/Downloads/Distance.gif
# wallpaper = HDMI-A-1, ~/Downloads/tokyo-night-buildings.jpg
